export {
  IconTrashSticker,
  IconTimerSticker,
  IconChefHatSticker,
  IconFridgeSticker,
  IconChartSticker,
  IconBellSticker,
  IconSettingsSticker,
  IconPlusSticker,
  IconEditSticker,
  IconSearchSticker,
  IconCalendarSticker,
  IconTipSticker,
  IconEggSticker,
  IconHeartSticker,
  IconStarSticker,
  IconCheckSticker,
  IconWarningSticker,
  IconErrorSticker,
  TimerIllustration,
  StickerIcons,
} from "./sticker-icons";
